// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfD55FybTLrSXiI7a_Ff3m7pM11pWu5OA',
    appId: '1:895977742080:web:8a134b6bc9aeca2a5b5de5',
    messagingSenderId: '895977742080',
    projectId: 'fluuter-learning',
    authDomain: 'fluuter-learning.firebaseapp.com',
    storageBucket: 'fluuter-learning.appspot.com',
    measurementId: 'G-J0KJ9XY4GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_OrIGoWMG4x3ZCTFVAM1YVdTM08-FQQ',
    appId: '1:895977742080:android:aff5fc1dcc0275925b5de5',
    messagingSenderId: '895977742080',
    projectId: 'fluuter-learning',
    storageBucket: 'fluuter-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxCfMDRWCV85UZHAl4jPULp4Lnjk8Gss',
    appId: '1:895977742080:ios:affb36a6f77c5f4d5b5de5',
    messagingSenderId: '895977742080',
    projectId: 'fluuter-learning',
    storageBucket: 'fluuter-learning.appspot.com',
    androidClientId: '895977742080-u8pfk0e5rr9kolgi35v5jlbop4h991ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
